"""empty message

Revision ID: e37d6114ded4
Revises: 
Create Date: 2021-04-14 18:12:41.815518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37d6114ded4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devicematrix',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('devicetype', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('jws', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('devicetype')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devicematrix')
    # ### end Alembic commands ###
